backend:
  name: git-gateway
  branch: main

media_folder: "image"
public_folder: "/image"

collections:
  - name: "bombons"
    label: "Bombons"
    files:
      - file: "produtos/bombons.json"
        label: "Lista de Bombons"
        name: "bombons"
        fields:
          - label: "Bombons"
            name: "items"
            widget: "list"
            label_singular: "Bombom"
            fields:
              - { label: "Nome", name: "title", widget: "string" }
              - { label: "Preço", name: "preco", widget: "string" }
              - { label: "Descrição", name: "descricao", widget: "text" }
              - label: "Imagem"
                name: "image"
                widget: "image"
                media_folder: "../image/bombons"
                public_folder: "/../image/bombons"
              - label: "Sabores"
                name: "sabores"
                widget: "list"
                required: false

  - name: "presentes"
    label: "Presentes"
    files:
      - file: "produtos/presentes.json"
        label: "Lista de Presentes"
        name: "presentes"
        fields:
          - label: "Presentes"
            name: "items"
            widget: "list"
            label_singular: "Presente"
            fields:
              - { label: "Nome", name: "title", widget: "string" }
              - { label: "Preço", name: "preco", widget: "string" }
              - { label: "Descrição", name: "descricao", widget: "text" }
              - label: "Imagem"
                name: "image"
                widget: "image"
                media_folder: "../image/presentes"
                public_folder: "/../image/presentes"
              - label: "Sabores"
                name: "sabores"
                widget: "list"
                required: false

  - name: "festas"
    label: "Festas"
    files:
      - file: "produtos/festas.json"
        label: "Lista de Festas"
        name: "festas"
        fields:
          - label: "Festas"
            name: "items"
            widget: "list"
            label_singular: "Item de Festa"
            fields:
              - { label: "Nome", name: "title", widget: "string" }
              - { label: "Preço", name: "preco", widget: "string" }
              - { label: "Descrição", name: "descricao", widget: "text" }
              - label: "Imagem"
                name: "image"
                widget: "image"
                media_folder: "../image/festas"
                public_folder: "/../image/festas"
              - label: "Sabores"
                name: "sabores"
                widget: "list"
                required: false

  - name: "pascoa"
    label: "Páscoa"
    files:
      - file: "produtos/pascoa.json"
        label: "Lista de Páscoa"
        name: "pascoa"
        fields:
          - label: "Páscoa"
            name: "items"
            widget: "list"
            label_singular: "Produto de Páscoa"
            fields:
              - { label: "Nome", name: "title", widget: "string" }
              - { label: "Preço", name: "preco", widget: "string" }
              - { label: "Descrição", name: "descricao", widget: "text" }
              - label: "Imagem"
                name: "image"
                widget: "image"
                media_folder: "../image/pascoa"
                public_folder: "/../image/pascoa"
              - label: "Sabores"
                name: "sabores"
                widget: "list"
                required: false
