backend:
  name: git-gateway
  branch: main

collections:
  - name: "bombons"
    label: "Bombons"
    files:
      - file: "produtos/bombons.json"
        label: "Lista de Bombons"
        name: "bombons"
        fields:
          - label: "Bombons"
            name: "items"
            widget: "list"
            media_folder: "image/bombons"
            public_folder: "/image/bombons"
            label_singular: "Bombom"
            fields:
              - { label: "Nome", name: "title", widget: "string" }
              - { label: "Preço", name: "preco", widget: "string" }
              - { label: "Descrição", name: "descricao", widget: "text" }
              - { label: "Imagem", name: "image", widget: "image" }


  - name: "presentes"
    label: "Presentes"
    files:
      - file: "produtos/presentes.json"
        label: "Lista de Presentes"
        name: "presentes"
        widget: "list"
        label_singular: "Presente"
        fields:
          - { label: "Nome", name: "title", widget: "string" }
          - { label: "Preço", name: "preco", widget: "string" }
          - { label: "Descrição", name: "descricao", widget: "text" }
          - { label: "Imagem", name: "image", widget: "image" }

  - name: "festas"
    label: "Festas"
    files:
      - file: "produtos/festas.json"
        label: "Lista de Festas"
        name: "festas"
        widget: "list"
        label_singular: "Item de Festa"
        fields:
          - { label: "Nome", name: "title", widget: "string" }
          - { label: "Preço", name: "preco", widget: "string" }
          - { label: "Descrição", name: "descricao", widget: "text" }
          - { label: "Imagem", name: "image", widget: "image" }

  - name: "pascoa"
    label: "Páscoa"
    files:
      - file: "produtos/pascoa.json"
        label: "Lista de Páscoa"
        name: "pascoa"
        widget: "list"
        label_singular: "Ovo de Páscoa"
        fields:
          - { label: "Nome", name: "title", widget: "string" }
          - { label: "Preço", name: "preco", widget: "string" }
          - { label: "Descrição", name: "descricao", widget: "text" }
          - { label: "Imagem", name: "image", widget: "image" }
