backend:
  name: git-gateway
  branch: main

media_folder: "image"
public_folder: "/image"

collections:
  - name: "bombons"
    label: "Bombons"
    folder: "produtos/bombons"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nome", name: "title", widget: "string" }
      - { label: "Preço", name: "preco", widget: "string" }
      - { label: "Descrição", name: "body", widget: "text" }
      - { label: "Imagem", name: "image", widget: "image" }

  - name: "presentes"
    label: "Presentes"
    folder: "produtos/presentes"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nome", name: "title", widget: "string" }
      - { label: "Preço", name: "preco", widget: "string" }
      - { label: "Descrição", name: "body", widget: "text" }
      - { label: "Imagem", name: "image", widget: "image" }

  - name: "festas"
    label: "Festas"
    folder: "produtos/festas"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nome", name: "title", widget: "string" }
      - { label: "Preço", name: "preco", widget: "string" }
      - { label: "Descrição", name: "body", widget: "text" }
      - { label: "Imagem", name: "image", widget: "image" }

  - name: "pascoa"
    label: "Páscoa"
    folder: "produtos/pascoa"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nome", name: "title", widget: "string" }
      - { label: "Preço", name: "preco", widget: "string" }
      - { label: "Descrição", name: "body", widget: "text" }
      - { label: "Imagem", name: "image", widget: "image" }
