backend:
  name: git-gateway
  branch: main

media_folder: "image"
public_folder: "/image"

collections:
  - name: "produtos"
    label: "Produtos"
    folder: "produtos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nome", name: "nome", widget: "string" }
      - { label: "Preço", name: "preco", widget: "string" }
      - { label: "Descrição", name: "descricao", widget: "text" }
      - { label: "Imagem", name: "imagem", widget: "image" }
